<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Fresh Cow Milk - 1L Bottle',
                'sku' => 'DAIRY-1001',
                'category' => 'milk',
                'price' => 90.00,
                'mrp' => 99.00,
                'discount_percent' => 9,
                'short_description' => 'Daily fresh • Hygienic bottling • Cold chain care',
                'description' => 'Fresh pasteurized milk, daily packed for consistent taste and quality. Cold-chain handling maintains freshness. Ideal for breakfast, tea, coffee, and daily use.',
                'badge' => 'Best Seller',
                'badge_color' => 'hot',
                'meta' => 'Fresh • Hygienic • Daily',
                'rating' => 4.6,
                'reviews_count' => 245,
                'variants' => [],
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 150,
                'shelf_life' => '2 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Tea, Coffee, Daily use',
                'image' => 'images/products-1.png',
                'images' => ['images/products-1.png', 'images/product-1.png'],
                'pack_sizes' => ['500ml', '1L', '2L'],
                'delivery_slots' => ['Morning', 'Evening', 'Express'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Fresh & Hygienic', 'description' => 'Daily packed with quality checks'],
                    ['icon' => '🧊', 'title' => 'Cold Chain Delivery', 'description' => 'Temperature safe till delivery'],
                    ['icon' => '🚚', 'title' => 'Quick Delivery', 'description' => 'Same-day delivery available'],
                ],
                'specifications' => [
                    'Type' => 'Pasteurized Cow Milk',
                    'Fat Content' => '3.5%',
                    'Protein' => '3.2g per 100ml',
                    'Packaging' => 'Sealed Bottle',
                ],
                'nutrition_info' => [
                    'Serving Size' => '100ml',
                    'Energy' => '60 kcal',
                    'Protein' => '3.2g',
                    'Fat' => '3.5g',
                    'Carbohydrate' => '4.8g',
                    'Calcium' => '120mg',
                ],
                'storage_instructions' => [
                    ['icon' => '🧊', 'title' => '0–4°C Store', 'description' => 'Refrigerated storage recommended'],
                    ['icon' => '⏱', 'title' => 'Use Within Shelf Life', 'description' => 'Consume as per packing date'],
                    ['icon' => '🧼', 'title' => 'Handle Hygienically', 'description' => 'Clean hands for handling'],
                ],
                'order' => 1,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Fresh Cow Milk - 500ml Bottle',
                'sku' => 'DAIRY-1002',
                'category' => 'milk',
                'price' => 50.00,
                'mrp' => 55.00,
                'discount_percent' => 9,
                'short_description' => 'Fresh taste • Quick delivery • Daily essential',
                'description' => 'Perfect half-liter pack for small families. Fresh pasteurized milk with consistent quality.',
                'badge' => 'New',
                'badge_color' => 'new',
                'meta' => 'Fresh • Quick • Essential',
                'rating' => 4.4,
                'reviews_count' => 180,
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 200,
                'shelf_life' => '2 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Tea, Coffee',
                'image' => 'images/products-2.png',
                'images' => ['images/products-2.png', 'images/product-2.png'],
                'pack_sizes' => ['500ml', '1L'],
                'delivery_slots' => ['Morning', 'Evening'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Fresh Daily', 'description' => 'Packed fresh every day'],
                    ['icon' => '🧊', 'title' => 'Cold Storage', 'description' => 'Maintained at optimal temperature'],
                ],
                'order' => 2,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Chocolate Flavoured Milk - 300ml',
                'sku' => 'DAIRY-2001',
                'category' => 'flavoured',
                'price' => 45.00,
                'mrp' => 55.00,
                'discount_percent' => 18,
                'short_description' => 'Smooth taste • Ready-to-drink • Bottle pack',
                'description' => 'Delicious chocolate flavored milk, perfect for kids and adults. Ready to drink anytime.',
                'badge' => null,
                'badge_color' => 'green',
                'meta' => 'Chocolate • Ready • Tasty',
                'rating' => 4.3,
                'reviews_count' => 156,
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 120,
                'shelf_life' => '3 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Snack, Kids',
                'image' => 'images/products-3.png',
                'images' => ['images/products-3.png', 'images/product-3.png'],
                'pack_sizes' => ['300ml', '500ml'],
                'delivery_slots' => ['Morning', 'Evening'],
                'features' => [
                    ['icon' => '🍫', 'title' => 'Rich Chocolate', 'description' => 'Smooth chocolate flavor'],
                    ['icon' => '✓', 'title' => 'Ready to Drink', 'description' => 'No preparation needed'],
                ],
                'order' => 3,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Classic Lassi - 300ml Bottle',
                'sku' => 'DAIRY-3001',
                'category' => 'lassi',
                'price' => 40.00,
                'mrp' => 49.00,
                'discount_percent' => 18,
                'short_description' => 'Thick & fresh • Ready-to-drink • Bottle pack',
                'description' => 'Traditional thick lassi made from fresh curd. Refreshing and nutritious.',
                'badge' => 'Popular',
                'badge_color' => 'hot',
                'meta' => 'Thick • Fresh • Traditional',
                'rating' => 4.5,
                'reviews_count' => 198,
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 100,
                'shelf_life' => '2 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Refreshment, Meal',
                'image' => 'images/products-4.png',
                'images' => ['images/products-4.png', 'images/product-4.png'],
                'pack_sizes' => ['300ml', '500ml'],
                'delivery_slots' => ['Morning', 'Evening'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Thick & Fresh', 'description' => 'Made from fresh curd'],
                    ['icon' => '🥤', 'title' => 'Ready to Drink', 'description' => 'Chilled and ready'],
                ],
                'order' => 4,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Chaas (Buttermilk) - 300ml Bottle',
                'sku' => 'DAIRY-4001',
                'category' => 'chaas',
                'price' => 25.00,
                'mrp' => 30.00,
                'discount_percent' => 17,
                'short_description' => 'Light & refreshing • Bottle pack • Daily drink',
                'description' => 'Light and refreshing buttermilk, perfect for digestion and hydration.',
                'badge' => null,
                'badge_color' => 'green',
                'meta' => 'Light • Refreshing • Healthy',
                'rating' => 4.2,
                'reviews_count' => 134,
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 150,
                'shelf_life' => '2 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Digestion, Hydration',
                'image' => 'images/products-1.png',
                'images' => ['images/products-1.png'],
                'pack_sizes' => ['300ml', '500ml'],
                'delivery_slots' => ['Morning', 'Evening'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Light & Healthy', 'description' => 'Good for digestion'],
                    ['icon' => '🥤', 'title' => 'Refreshing', 'description' => 'Perfect for summer'],
                ],
                'order' => 5,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Fresh Curd (Dahi) - 500g',
                'sku' => 'DAIRY-5001',
                'category' => 'curd',
                'price' => 60.00,
                'mrp' => 70.00,
                'discount_percent' => 14,
                'short_description' => 'Thick curd • Fresh set • Daily use',
                'description' => 'Fresh thick curd, perfectly set. Ideal for daily consumption and cooking.',
                'badge' => null,
                'badge_color' => 'green',
                'meta' => 'Thick • Fresh • Daily',
                'rating' => 4.4,
                'reviews_count' => 167,
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 80,
                'shelf_life' => '3 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Eating, Cooking',
                'image' => 'images/products-2.png',
                'images' => ['images/products-2.png'],
                'pack_sizes' => ['250g', '500g', '1kg'],
                'delivery_slots' => ['Morning', 'Evening'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Thick & Fresh', 'description' => 'Perfectly set curd'],
                    ['icon' => '🥄', 'title' => 'Versatile', 'description' => 'For eating and cooking'],
                ],
                'order' => 6,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Fresh Paneer - 200g',
                'sku' => 'DAIRY-6001',
                'category' => 'paneer',
                'price' => 85.00,
                'mrp' => 99.00,
                'discount_percent' => 14,
                'short_description' => 'Soft texture • Fresh pack • Consistent quality',
                'description' => 'Fresh soft paneer, perfect for all your cooking needs. Made from pure milk.',
                'badge' => null,
                'badge_color' => 'green',
                'meta' => 'Soft • Fresh • Pure',
                'rating' => 4.3,
                'reviews_count' => 145,
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 60,
                'shelf_life' => '3 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Cooking, Curries',
                'image' => 'images/products-3.png',
                'images' => ['images/products-3.png'],
                'pack_sizes' => ['200g', '500g'],
                'delivery_slots' => ['Morning', 'Evening'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Soft Texture', 'description' => 'Perfect for cooking'],
                    ['icon' => '🥛', 'title' => 'Pure Milk', 'description' => 'Made from fresh milk'],
                ],
                'order' => 7,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Fresh Cream - 200ml',
                'sku' => 'DAIRY-7001',
                'category' => 'cream',
                'price' => 75.00,
                'mrp' => 89.00,
                'discount_percent' => 16,
                'short_description' => 'Rich & smooth • Fresh pack • Daily kitchen',
                'description' => 'Rich and smooth fresh cream for cooking and desserts. Premium quality.',
                'badge' => null,
                'badge_color' => 'green',
                'meta' => 'Rich • Smooth • Premium',
                'rating' => 4.1,
                'reviews_count' => 112,
                'variants' => [],
                'stock_status' => 'available',
                'stock_quantity' => 50,
                'shelf_life' => '4 Days',
                'storage_temp' => '0–4°C',
                'best_for' => 'Cooking, Desserts',
                'image' => 'images/products-4.png',
                'images' => ['images/products-4.png'],
                'pack_sizes' => ['200ml', '500ml'],
                'delivery_slots' => ['Morning', 'Evening'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Rich & Smooth', 'description' => 'Premium quality cream'],
                    ['icon' => '🍰', 'title' => 'Versatile', 'description' => 'For cooking and desserts'],
                ],
                'order' => 8,
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}

